spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhosting-db
    username: sa

  h2:
    console:
      enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
