spring:
  profiles:
    group:
      socket: socket
      rmq: rabbitmq
    active: socket

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhosting-db
    username: sa

  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false

--- # forwarding by Socket
spring:
  config:
    activate:
      on-profile: socket

--- # forwarding by RabbitMQ
spring:
  config:
    activate:
      on-profile: rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
---